title: Faisal Hossain
description: M.S. Information Systems · Baruch College
admin_name: Faisal Hossain
footer_text: Faisal Hossain

github_username: faisalhossainnyc

enable_nav: false
enable_contact: false

plugins:
  - jekyll-paginate

paginate: 10
